// This script is injected into docs.google.com/document/d/*
// It checks if the URL has the cv_tailor=true query parameter, indicating it was generated by our extension

function checkAndInjectUI() {
    const params = new URLSearchParams(window.location.search);
    if (params.get('cv_tailor') !== 'true') return;

    const jobTitle = params.get('jobTitle');
    const company = params.get('company');
    const cvName = params.get('cvName');

    // Extract document ID from the URL pathway
    const pathParts = window.location.pathname.split('/');
    const dIndex = pathParts.indexOf('d');
    const docId = pathParts[dIndex + 1];

    if (!docId) return;

    // Check if UI already exists
    if (document.getElementById('cv-tailor-approval-ui')) return;

    // Create the floating UI container
    const container = document.createElement('div');
    container.id = 'cv-tailor-approval-ui';

    const title = document.createElement('div');
    title.className = 'cv-tailor-title';
    title.textContent = 'CV Tailor - Approval needed'

    const desc = document.createElement('div');
    desc.className = 'cv-tailor-desc';
    desc.textContent = `Review your newly tailored CV for ${company}. Make any manual edits if necessary, then click Approve to auto-download as a PDF.`;

    const buttonGroup = document.createElement('div');
    buttonGroup.className = 'cv-tailor-btn-group';

    const approveBtn = document.createElement('button');
    approveBtn.className = 'cv-tailor-btn cv-tailor-btn-primary';
    approveBtn.innerHTML = `
        <span class="cv-tailor-btn-content">
            <svg class="cv-tailor-spinner cv-tailor-hidden" id="cv-tailor-approve-spinner" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-opacity="0.25" stroke-width="4"></circle>
                <path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" stroke-width="4" stroke-linecap="round"></path>
            </svg>
            <span id="cv-tailor-approve-text">Approve & Download PDF</span>
        </span>
    `;

    const retryBtn = document.createElement('button');
    retryBtn.className = 'cv-tailor-btn cv-tailor-btn-secondary';
    retryBtn.innerHTML = `
        <span class="cv-tailor-btn-content">
            <svg class="cv-tailor-spinner cv-tailor-hidden" id="cv-tailor-retry-spinner" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-opacity="0.25" stroke-width="4"></circle>
                <path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" stroke-width="4" stroke-linecap="round"></path>
            </svg>
            <span id="cv-tailor-retry-text">Try Again (AI Rewrite)</span>
        </span>
    `;

    const statusMsg = document.createElement('div');
    statusMsg.className = 'cv-tailor-status';

    approveBtn.addEventListener('click', () => {
        const approveSpinner = document.getElementById('cv-tailor-approve-spinner');
        const approveText = document.getElementById('cv-tailor-approve-text');

        approveBtn.disabled = true;
        retryBtn.disabled = true;
        if (approveSpinner) approveSpinner.classList.remove('cv-tailor-hidden');
        if (approveText) approveText.textContent = 'Downloading...';

        statusMsg.textContent = 'Generating PDF from Google Drive...';
        statusMsg.style.color = '#6b7280';

        chrome.runtime.sendMessage({
            action: 'download_pdf',
            data: {
                docId: docId,
                jobTitle: jobTitle,
                company: company,
                cvName: cvName
            }
        }, (response) => {
            if (response && response.success) {
                statusMsg.textContent = 'Downloaded successfully! Closing tab...';
                statusMsg.style.color = '#10b981';
                setTimeout(() => container.remove(), 2000);
            } else {
                const approveSpinner = document.getElementById('cv-tailor-approve-spinner');
                const approveText = document.getElementById('cv-tailor-approve-text');

                approveBtn.disabled = false;
                retryBtn.disabled = false;
                if (approveSpinner) approveSpinner.classList.add('cv-tailor-hidden');
                if (approveText) approveText.textContent = 'Approve & Download PDF';

                statusMsg.textContent = 'Error: ' + (response ? response.error : 'Unknown');
                statusMsg.style.color = '#ef4444';
            }
        });
    });

    retryBtn.addEventListener('click', () => {
        const retrySpinner = document.getElementById('cv-tailor-retry-spinner');
        const retryText = document.getElementById('cv-tailor-retry-text');

        approveBtn.disabled = true;
        retryBtn.disabled = true;
        if (retrySpinner) retrySpinner.classList.remove('cv-tailor-hidden');
        if (retryText) retryText.textContent = 'Retrying...';

        statusMsg.textContent = 'Deleting current doc and asking AI to rewrite...';
        statusMsg.style.color = '#6b7280';

        chrome.runtime.sendMessage({
            action: 'retry_tailor',
            data: { docId: docId }
        }, (response) => {
            if (response && response.success && response.newDocId) {
                statusMsg.textContent = 'Success! Opening new version...';
                statusMsg.style.color = '#10b981';
                const queryParams = new URLSearchParams({
                    cv_tailor: "true",
                    jobTitle: jobTitle,
                    company: company,
                    cvName: cvName
                });
                // The background script deleted the old file, so we navigate the CURRENT tab to the new one
                window.location.href = `https://docs.google.com/document/d/${response.newDocId}/edit?${queryParams.toString()}`;
            } else {
                const retrySpinner = document.getElementById('cv-tailor-retry-spinner');
                const retryText = document.getElementById('cv-tailor-retry-text');

                approveBtn.disabled = false;
                retryBtn.disabled = false;
                if (retrySpinner) retrySpinner.classList.add('cv-tailor-hidden');
                if (retryText) retryText.textContent = 'Try Again (AI Rewrite)';

                statusMsg.textContent = 'Error: ' + (response ? response.error : 'Unknown');
                statusMsg.style.color = '#ef4444';
            }
        });
    });

    buttonGroup.appendChild(approveBtn);
    buttonGroup.appendChild(retryBtn);

    container.appendChild(title);
    container.appendChild(desc);
    container.appendChild(buttonGroup);
    container.appendChild(statusMsg);

    document.body.appendChild(container);
}

// Docs is an SPA, so we observe for navigation changes or just run it periodically 
// because the script might run before the history API pushState happens.
checkAndInjectUI();
setInterval(checkAndInjectUI, 2000);
